export { default as CollapsibleRoot } from './CollapsibleRoot.vue'
export { default as CollapsibleTrigger } from './CollapsibleTrigger.vue'
export { default as CollapsibleContent } from './CollapsibleContent.vue'
export type { CollapsibleRootProps, CollapsibleTriggerProps, CollapsibleContentProps } from './types'
export { injectCollapsibleRootContext, provideCollapsibleRootContext } from './types'
